package net.fis.struts;


/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.fis.hibernate.Categoria;
import net.fis.hibernate.CategoriaDAO;

import org.apache.commons.beanutils.PropertyUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;


/**
 * MyEclipse Struts Creation date: 11-16-2006
 * 
 * XDoclet definition:
 * 
 * @struts.action input="/abm/categoria.jsp" validate="true"
 */
public class CategoriaAction extends DispatchAction
{

    /**
     * 
     * @param newMessage
     * @param request
     */
    public void setActionMessages(String newMessage, HttpServletRequest request)
    {

        ActionMessages messages = new ActionMessages();
        ActionMessage message = new ActionMessage(newMessage);

        messages.add(ActionMessages.GLOBAL_MESSAGE, message);
        saveMessages(request, messages);
    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward listAll(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        HttpSession session = request.getSession();

        CategoriaDAO categoriaDAO = new CategoriaDAO();

        List resultados = categoriaDAO.findAll(" order by catId");

        session.setAttribute("categorias", resultados);
        ActionForward forward = mapping.findForward("categorias");

        return forward;

    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @throws Exception
     */
    public void show(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        CategoriaDAO categoriaDAO = new CategoriaDAO();
        DynaActionForm daf = (DynaActionForm) form;
        Categoria categoria = categoriaDAO.findById(new Integer((String) daf.getString("id")));

        daf.set("hasta", categoria.getCatHasta().toString());
        daf.set("desde", categoria.getCatDesde().toString());
        daf.set("descripcion", categoria.getCatDescripcion());
        daf.set("minimo", String.valueOf(categoria.getCatMinJug()));
        daf.set("id", String.valueOf(categoria.getCatId()));

    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward listOne(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        show(mapping, form, request, response);

        DynaActionForm daf = (DynaActionForm) form;

        daf.set("metodo", "mostrar");
        ActionForward forward = mapping.findForward("select");

        return forward;
    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward setInsert(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        DynaActionForm daf = (DynaActionForm) form;
        daf.set("metodo", "alta");

        ActionForward forward = mapping.findForward("create");

        return forward;
    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward insert(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        Categoria categoria = new Categoria();
        categoria.setCatDescripcion((String) PropertyUtils.getSimpleProperty(form, "descripcion"));
        // categoria.setCatDesde((String) PropertyUtils.getSimpleProperty(
        // form, "desde"));
        // categoria.setCatHasta((String) PropertyUtils.getSimpleProperty(
        // form, "hasta"));
        categoria.setCatMinJug(new Integer((String) PropertyUtils.getSimpleProperty(form, "minimo")));

        CategoriaDAO categoriaDAO = new CategoriaDAO();
        categoriaDAO.save(categoria);

        ActionForward forward = mapping.findForward("success");

        return forward;
    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward delete(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        CategoriaDAO categoriaDAO = new CategoriaDAO();
        Categoria categoria = categoriaDAO.findById(new Integer((String) PropertyUtils.getSimpleProperty(form, "id")));
        categoriaDAO.delete(categoria);

        ActionForward forward = mapping.findForward("success");

        return forward;
    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward setUpdate(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        show(mapping, form, request, response);

        DynaActionForm daf = (DynaActionForm) form;

        daf.set("metodo", "modificacion");
        ActionForward forward = mapping.findForward("update");

        return forward;
    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward update(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {

        Categoria categoria = new Categoria();
        categoria.setCatId(new Integer((String) PropertyUtils.getSimpleProperty(form, "id")));
        categoria.setCatDescripcion((String) PropertyUtils.getSimpleProperty(form, "descripcion"));
        // categoria.setCatDesde((String) PropertyUtils.getSimpleProperty(
        // form, "desde"));
        // categoria.setCatHasta((String) PropertyUtils.getSimpleProperty(
        // form, "hasta"));
        categoria.setCatMinJug(new Integer((String) PropertyUtils.getSimpleProperty(form, "minimo")));

        CategoriaDAO categoriaDAO = new CategoriaDAO();
        categoriaDAO.update(categoria);

        ActionForward forward = mapping.findForward("success");

        return forward;
    }

    /**
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     * @throws Exception
     */
    public ActionForward unespecified(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception
    {
        return listAll(mapping, form, request, response);
    }

}
