package net.fis.hibernate;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Categoria generated by MyEclipse - Hibernate Tools
 */

public class Categoria implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = -3086067971818753875L;

    private Integer           catId;

    private String            catDescripcion;

    private Date              catDesde;

    private Date              catHasta;

    private Integer           catMinJug;

    private Set               jugadors         = new HashSet(0);

    // Constructors

    /** default constructor */
    public Categoria() {
    }

    /** minimal constructor */
    public Categoria(String catDescripcion, Date catDesde, Date catHasta) {
        this.catDescripcion = catDescripcion;
        this.catDesde = catDesde;
        this.catHasta = catHasta;
    }

    /** full constructor */
    public Categoria(String catDescripcion, Date catDesde, Date catHasta, Integer catMinJug, Set jugadors) {
        this.catDescripcion = catDescripcion;
        this.catDesde = catDesde;
        this.catHasta = catHasta;
        this.catMinJug = catMinJug;
        this.jugadors = jugadors;
    }

    // Property accessors

    public Integer getCatId()
    {
        return this.catId;
    }

    public void setCatId(Integer catId)
    {
        this.catId = catId;
    }

    public String getCatDescripcion()
    {
        return this.catDescripcion;
    }

    public void setCatDescripcion(String catDescripcion)
    {
        this.catDescripcion = catDescripcion;
    }

    public Date getCatDesde()
    {
        return this.catDesde;
    }

    public void setCatDesde(Date catDesde)
    {
        this.catDesde = catDesde;
    }

    public Date getCatHasta()
    {
        return this.catHasta;
    }

    public void setCatHasta(Date catHasta)
    {
        this.catHasta = catHasta;
    }

    public Integer getCatMinJug()
    {
        return this.catMinJug;
    }

    public void setCatMinJug(Integer catMinJug)
    {
        this.catMinJug = catMinJug;
    }

    public Set getJugadors()
    {
        return this.jugadors;
    }

    public void setJugadors(Set jugadors)
    {
        this.jugadors = jugadors;
    }

}
