package net.fis.hibernate;


/**
 * FichaMedica generated by MyEclipse - Hibernate Tools
 */

public class FichaMedica implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = -3437391542379872394L;

    private Integer           fmId;

    private Medico            medico;

    private Jugador           jugador;

    private String            fmEstado;

    private String            fmAlergias;

    private String            fmCardiopatias;

    private String            fmAntecedentes;

    private String            fmHistorial;

    private String            fmBucoDen;

    // Constructors

    /** default constructor */
    public FichaMedica() {
    }

    /** minimal constructor */
    public FichaMedica(Medico medico, Jugador jugador, String fmEstado, String fmAlergias, String fmCardiopatias, String fmAntecedentes, String fmHistorial) {
        this.medico = medico;
        this.jugador = jugador;
        this.fmEstado = fmEstado;
        this.fmAlergias = fmAlergias;
        this.fmCardiopatias = fmCardiopatias;
        this.fmAntecedentes = fmAntecedentes;
        this.fmHistorial = fmHistorial;
    }

    /** full constructor */
    public FichaMedica(Medico medico, Jugador jugador, String fmEstado, String fmAlergias, String fmCardiopatias, String fmAntecedentes, String fmHistorial,
            String fmBucoDen) {
        this.medico = medico;
        this.jugador = jugador;
        this.fmEstado = fmEstado;
        this.fmAlergias = fmAlergias;
        this.fmCardiopatias = fmCardiopatias;
        this.fmAntecedentes = fmAntecedentes;
        this.fmHistorial = fmHistorial;
        this.fmBucoDen = fmBucoDen;
    }

    // Property accessors

    public Integer getFmId()
    {
        return this.fmId;
    }

    public void setFmId(Integer fmId)
    {
        this.fmId = fmId;
    }

    public Medico getMedico()
    {
        return this.medico;
    }

    public void setMedico(Medico medico)
    {
        this.medico = medico;
    }

    public Jugador getJugador()
    {
        return this.jugador;
    }

    public void setJugador(Jugador jugador)
    {
        this.jugador = jugador;
    }

    public String getFmEstado()
    {
        return this.fmEstado;
    }

    public void setFmEstado(String fmEstado)
    {
        this.fmEstado = fmEstado;
    }

    public String getFmAlergias()
    {
        return this.fmAlergias;
    }

    public void setFmAlergias(String fmAlergias)
    {
        this.fmAlergias = fmAlergias;
    }

    public String getFmCardiopatias()
    {
        return this.fmCardiopatias;
    }

    public void setFmCardiopatias(String fmCardiopatias)
    {
        this.fmCardiopatias = fmCardiopatias;
    }

    public String getFmAntecedentes()
    {
        return this.fmAntecedentes;
    }

    public void setFmAntecedentes(String fmAntecedentes)
    {
        this.fmAntecedentes = fmAntecedentes;
    }

    public String getFmHistorial()
    {
        return this.fmHistorial;
    }

    public void setFmHistorial(String fmHistorial)
    {
        this.fmHistorial = fmHistorial;
    }

    public String getFmBucoDen()
    {
        return this.fmBucoDen;
    }

    public void setFmBucoDen(String fmBucoDen)
    {
        this.fmBucoDen = fmBucoDen;
    }

}
