package net.fis.hibernate;


/**
 * RolPermisoId generated by MyEclipse - Hibernate Tools
 */

public class RolPermisoId implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = 3462671003230947413L;

    private Rol               rol;

    private Permiso           permiso;

    // Constructors

    /** default constructor */
    public RolPermisoId() {
    }

    /** full constructor */
    public RolPermisoId(Rol rol, Permiso permiso) {
        this.rol = rol;
        this.permiso = permiso;
    }

    // Property accessors

    public Rol getRol()
    {
        return this.rol;
    }

    public void setRol(Rol rol)
    {
        this.rol = rol;
    }

    public Permiso getPermiso()
    {
        return this.permiso;
    }

    public void setPermiso(Permiso permiso)
    {
        this.permiso = permiso;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RolPermisoId))
            return false;
        RolPermisoId castOther = (RolPermisoId) other;

        return ((this.getRol() == castOther.getRol()) || (this.getRol() != null && castOther.getRol() != null && this.getRol().equals(castOther.getRol())))
                && ((this.getPermiso() == castOther.getPermiso()) || (this.getPermiso() != null && castOther.getPermiso() != null && this.getPermiso().equals(
                        castOther.getPermiso())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getRol() == null ? 0 : this.getRol().hashCode());
        result = 37 * result + (getPermiso() == null ? 0 : this.getPermiso().hashCode());
        return result;
    }

}
