package net.fis.hibernate;

/**
 * ClubId generated by MyEclipse - Hibernate Tools
 */

public class ClubId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3660173293620764408L;

	// Fields

	private Integer clubId;

	private Federacion federacion;

	// Constructors

	/** default constructor */
	public ClubId() {
	}

	/** full constructor */
	public ClubId(Integer clubId, Federacion federacion) {
		this.clubId = clubId;
		this.federacion = federacion;
	}

	// Property accessors

	public Integer getClubId() {
		return this.clubId;
	}

	public void setClubId(Integer clubId) {
		this.clubId = clubId;
	}

	public Federacion getFederacion() {
		return this.federacion;
	}

	public void setFederacion(Federacion federacion) {
		this.federacion = federacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClubId))
			return false;
		ClubId castOther = (ClubId) other;

		return ((this.getClubId() == castOther.getClubId()) || (this
				.getClubId() != null
				&& castOther.getClubId() != null && this.getClubId().equals(
				castOther.getClubId())))
				&& ((this.getFederacion() == castOther.getFederacion()) || (this
						.getFederacion() != null
						&& castOther.getFederacion() != null && this
						.getFederacion().equals(castOther.getFederacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getClubId() == null ? 0 : this.getClubId().hashCode());
		result = 37
				* result
				+ (getFederacion() == null ? 0 : this.getFederacion()
						.hashCode());
		return result;
	}

}