package net.fis.hibernate;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Jugador generated by MyEclipse - Hibernate Tools
 */

public class Jugador implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = 1845367560280874387L;

    private Integer           jugId;

    private Club              club;

    private Categoria         categoria;

    private String            jugFederado;

    private String            jugNombre;

    private String            jugApellido;

    private Date              jugFechaNac;

    private Set               avisos           = new HashSet(0);

    private Set               fichaMedicas     = new HashSet(0);

    // Constructors

    /** default constructor */
    public Jugador() {
    }

    /** minimal constructor */
    public Jugador(Club club, Categoria categoria, String jugFederado, String jugNombre, String jugApellido, Date jugFechaNac) {
        this.club = club;
        this.categoria = categoria;
        this.jugFederado = jugFederado;
        this.jugNombre = jugNombre;
        this.jugApellido = jugApellido;
        this.jugFechaNac = jugFechaNac;
    }

    /** full constructor */
    public Jugador(Club club, Categoria categoria, String jugFederado, String jugNombre, String jugApellido, Date jugFechaNac, Set avisos, Set fichaMedicas) {
        this.club = club;
        this.categoria = categoria;
        this.jugFederado = jugFederado;
        this.jugNombre = jugNombre;
        this.jugApellido = jugApellido;
        this.jugFechaNac = jugFechaNac;
        this.avisos = avisos;
        this.fichaMedicas = fichaMedicas;
    }

    // Property accessors

    public Integer getJugId()
    {
        return this.jugId;
    }

    public void setJugId(Integer jugId)
    {
        this.jugId = jugId;
    }

    public Club getClub()
    {
        return this.club;
    }

    public void setClub(Club club)
    {
        this.club = club;
    }

    public Categoria getCategoria()
    {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria)
    {
        this.categoria = categoria;
    }

    public String getJugFederado()
    {
        return this.jugFederado;
    }

    public void setJugFederado(String jugFederado)
    {
        this.jugFederado = jugFederado;
    }

    public String getJugNombre()
    {
        return this.jugNombre;
    }

    public void setJugNombre(String jugNombre)
    {
        this.jugNombre = jugNombre;
    }

    public String getJugApellido()
    {
        return this.jugApellido;
    }

    public void setJugApellido(String jugApellido)
    {
        this.jugApellido = jugApellido;
    }

    public Date getJugFechaNac()
    {
        return this.jugFechaNac;
    }

    public void setJugFechaNac(Date jugFechaNac)
    {
        this.jugFechaNac = jugFechaNac;
    }

    public Set getAvisos()
    {
        return this.avisos;
    }

    public void setAvisos(Set avisos)
    {
        this.avisos = avisos;
    }

    public Set getFichaMedicas()
    {
        return this.fichaMedicas;
    }

    public void setFichaMedicas(Set fichaMedicas)
    {
        this.fichaMedicas = fichaMedicas;
    }

}
