package net.fis.hibernate;

import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by MyEclipse - Hibernate Tools
 */

public class Medico implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2556301385860443950L;

	private Integer medId;

	private String medNombre;

	private String medApellido;

	private String medMatricula;

	private Set fichaMedicas = new HashSet(0);

	// Constructors

	/** default constructor */
	public Medico() {
	}

	/** minimal constructor */
	public Medico(String medNombre, String medApellido, String medMatricula) {
		this.medNombre = medNombre;
		this.medApellido = medApellido;
		this.medMatricula = medMatricula;
	}

	/** full constructor */
	public Medico(String medNombre, String medApellido, String medMatricula,
			Set fichaMedicas) {
		this.medNombre = medNombre;
		this.medApellido = medApellido;
		this.medMatricula = medMatricula;
		this.fichaMedicas = fichaMedicas;
	}

	// Property accessors

	public Integer getMedId() {
		return this.medId;
	}

	public void setMedId(Integer medId) {
		this.medId = medId;
	}

	public String getMedNombre() {
		return this.medNombre;
	}

	public void setMedNombre(String medNombre) {
		this.medNombre = medNombre;
	}

	public String getMedApellido() {
		return this.medApellido;
	}

	public void setMedApellido(String medApellido) {
		this.medApellido = medApellido;
	}

	public String getMedMatricula() {
		return this.medMatricula;
	}

	public void setMedMatricula(String medMatricula) {
		this.medMatricula = medMatricula;
	}

	public Set getFichaMedicas() {
		return this.fichaMedicas;
	}

	public void setFichaMedicas(Set fichaMedicas) {
		this.fichaMedicas = fichaMedicas;
	}

}