package net.fis.hibernate;


import java.util.HashSet;
import java.util.Set;


/**
 * Permiso generated by MyEclipse - Hibernate Tools
 */

public class Permiso implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = -3102111617526261440L;

    private Integer           perId;

    private String            perDescripcion;

    private Set               rolPermisos      = new HashSet(0);

    // Constructors

    /** default constructor */
    public Permiso() {
    }

    /** minimal constructor */
    public Permiso(String perDescripcion) {
        this.perDescripcion = perDescripcion;
    }

    /** full constructor */
    public Permiso(String perDescripcion, Set rolPermisos) {
        this.perDescripcion = perDescripcion;
        this.rolPermisos = rolPermisos;
    }

    // Property accessors

    public Integer getPerId()
    {
        return this.perId;
    }

    public void setPerId(Integer perId)
    {
        this.perId = perId;
    }

    public String getPerDescripcion()
    {
        return this.perDescripcion;
    }

    public void setPerDescripcion(String perDescripcion)
    {
        this.perDescripcion = perDescripcion;
    }

    public Set getRolPermisos()
    {
        return this.rolPermisos;
    }

    public void setRolPermisos(Set rolPermisos)
    {
        this.rolPermisos = rolPermisos;
    }

}
