package net.fis.hibernate;


import java.util.HashSet;
import java.util.Set;


/**
 * Rol generated by MyEclipse - Hibernate Tools
 */

public class Rol implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = 726241681888953635L;

    private Integer           rolId;

    private String            rolDescripcion;

    private Set               usuarios         = new HashSet(0);

    private Set               rolPermisos      = new HashSet(0);

    // Constructors

    /** default constructor */
    public Rol() {
    }

    /** minimal constructor */
    public Rol(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }

    /** full constructor */
    public Rol(String rolDescripcion, Set usuarios, Set rolPermisos) {
        this.rolDescripcion = rolDescripcion;
        this.usuarios = usuarios;
        this.rolPermisos = rolPermisos;
    }

    // Property accessors

    public Integer getRolId()
    {
        return this.rolId;
    }

    public void setRolId(Integer rolId)
    {
        this.rolId = rolId;
    }

    public String getRolDescripcion()
    {
        return this.rolDescripcion;
    }

    public void setRolDescripcion(String rolDescripcion)
    {
        this.rolDescripcion = rolDescripcion;
    }

    public Set getUsuarios()
    {
        return this.usuarios;
    }

    public void setUsuarios(Set usuarios)
    {
        this.usuarios = usuarios;
    }

    public Set getRolPermisos()
    {
        return this.rolPermisos;
    }

    public void setRolPermisos(Set rolPermisos)
    {
        this.rolPermisos = rolPermisos;
    }

}
