package net.fis.hibernate;


/**
 * RolPermiso generated by MyEclipse - Hibernate Tools
 */

public class RolPermiso implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = 7428343233568107386L;

    private RolPermisoId      id;

    // Constructors

    /** default constructor */
    public RolPermiso() {
    }

    // Property accessors

    public RolPermisoId getId()
    {
        return this.id;
    }

    public void setId(RolPermisoId id)
    {
        this.id = id;
    }

}
