package net.fis.hibernate;


/**
 * Usuario generated by MyEclipse - Hibernate Tools
 */

public class Usuario implements java.io.Serializable
{

    // Fields

    /**
     * 
     */
    private static final long serialVersionUID = 322230959092160498L;

    private Integer usuId;

    private Rol     rol;

    private String  usuNombre;

    private String  usuApellido;

    private String  usuPassword;

    // Constructors

    /** default constructor */
    public Usuario() {
    }

    /** full constructor */
    public Usuario(Rol rol, String usuNombre, String usuApellido, String usuPassword) {
        this.rol = rol;
        this.usuNombre = usuNombre;
        this.usuApellido = usuApellido;
        this.usuPassword = usuPassword;
    }

    // Property accessors

    public Integer getUsuId()
    {
        return this.usuId;
    }

    public void setUsuId(Integer usuId)
    {
        this.usuId = usuId;
    }

    public Rol getRol()
    {
        return this.rol;
    }

    public void setRol(Rol rol)
    {
        this.rol = rol;
    }

    public String getUsuNombre()
    {
        return this.usuNombre;
    }

    public void setUsuNombre(String usuNombre)
    {
        this.usuNombre = usuNombre;
    }

    public String getUsuApellido()
    {
        return this.usuApellido;
    }

    public void setUsuApellido(String usuApellido)
    {
        this.usuApellido = usuApellido;
    }

    public String getUsuPassword()
    {
        return this.usuPassword;
    }

    public void setUsuPassword(String usuPassword)
    {
        this.usuPassword = usuPassword;
    }

}
